trigger:
- none

pool:
  name: PredatorAgentPool

variables:
- group: SQLDB        # contains POSTGRES_PASSWORD
- group: OpenAI       # contains OPENAI_API_KEY
- group: GHCR         # contains GHCR_USERNAME, GHCR_TOKEN

steps:

# 1️⃣ Build Docker image (Dockerfile is in backend/)
- script: |
    echo "Building GeekFormAI backend image..."
    docker build \
      -t ghcr.io/$(GHCR_USERNAME)/geekform-backend:latest \
      WebApps/GeekFormAI/backend
  displayName: Build Docker image

# 2️⃣ Login to GitHub Container Registry
- script: |
    echo "Logging into GHCR..."
    echo "$(GHCR_TOKEN)" | docker login ghcr.io \
      -u $(GHCR_USERNAME) \
      --password-stdin
  displayName: Login to GHCR

# 3️⃣ Push image to GHCR
- script: |
    echo "Pushing image to GHCR..."
    docker push ghcr.io/$(GHCR_USERNAME)/geekform-backend:latest
  displayName: Push image to GHCR

# 4️⃣ Ensure geekform namespace exists
- script: |
    echo "Ensuring geekform namespace exists..."
    kubectl create namespace geekform --dry-run=client -o yaml | kubectl apply -f -
  displayName: Ensure namespace

# 5️⃣ Apply / update Kubernetes secrets
- script: |
    echo "Applying Kubernetes secrets..."
    kubectl create secret generic geekform-secrets \
      --namespace geekform \
      --from-literal=POSTGRES_USER=geekform \
      --from-literal=POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
      --from-literal=POSTGRES_DB=geekformdb \
      --from-literal=DATABASE_URL=postgresql://geekform:$(POSTGRES_PASSWORD)@postgres:5432/geekformdb \
      --from-literal=OPENAI_API_KEY=$(OPENAI_API_KEY) \
      --dry-run=client -o yaml | kubectl apply -f -
  displayName: Apply app secrets

# 6️⃣ Deploy GeekFormAI to k3s
- script: |
    echo "Deploying GeekFormAI to k3s..."
    kubectl apply -f WebApps/GeekFormAI/GeekFormAI.yml
  displayName: Deploy GeekFormAI

# 7️⃣ Restart API pods to pull new image
- script: |
    echo "Restarting GeekFormAI deployment..."
    kubectl rollout restart deployment/geekform-ai -n geekform
  displayName: Restart GeekFormAI pods
