trigger:
- none

pool:
  name: PredatorAgentPool

variables:
- group: SQLDB        # contains POSTGRES_PASSWORD
- group: OpenAI       # contains OPENAI_API_KEY

steps:

# 1️⃣ Build Docker image
- script: |
    echo "Building GeekFormAI backend image..."
    docker build \
    -t geekform-backend:latest \
    -f WebApps/GeekFormAI/backend/Dockerfile \
    WebApps/GeekFormAI/backend

  displayName: Build Docker image

# 2️⃣ Load image into k3s (FIXED)
- script: |
    echo "Loading image into k3s..."
    docker save geekform-backend:latest | sudo k3s ctr images import -
  displayName: Load image into k3s


# 3️⃣ Ensure namespace exists
- script: |
    echo "Ensuring geekform namespace exists..."
    kubectl create namespace geekform --dry-run=client -o yaml | kubectl apply -f -
  displayName: Ensure namespace

# 4️⃣ Apply secrets
- script: |
    echo "Applying secrets..."
    kubectl create secret generic geekform-secrets \
      --namespace geekform \
      --from-literal=POSTGRES_USER=geekform \
      --from-literal=POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
      --from-literal=POSTGRES_DB=geekformdb \
       --from-literal=DATABASE_URL=postgresql://geekform:$(POSTGRES_PASSWORD)@postgres:5432/geekformdb \
      --from-literal=OPENAI_API_KEY=$(OPENAI_API_KEY) \
      --dry-run=client -o yaml | kubectl apply -f -
  displayName: Apply secrets

# 5️⃣ Deploy GeekFormAI stack
- script: |
    echo "Deploying GeekFormAI to k3s..."
    kubectl apply -f WebApps/GeekFormAI/GeekFormAI.yml
  displayName: Deploy GeekFormAI
# 6 Restart nodes after apply
- script: |
    echo "Restarting GeekFormAI deployment..."
    kubectl rollout restart deployment/geekform-ai -n geekform
  displayName: Restart API pods
# 7 Verify Pods are working
- script: |
    kubectl get pods -n geekform
  displayName: Verify pods

