apiVersion: v1
kind: Namespace
metadata:
  name: geekform
---
apiVersion: v1
kind: Secret
metadata:
  name: geekform-secrets
  namespace: geekform
type: Opaque
stringData:
  POSTGRES_USER: geekform
  POSTGRES_PASSWORD: geekform
  POSTGRES_DB: geekformdb
  DATABASE_URL: postgresql://geekform:geekform@postgres:5432/geekformdb
  OPENAI_API_KEY: sk-REPLACE_ME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: geekform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: geekform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: geekform-secrets
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: geekform
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geekform-ai
  namespace: geekform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geekform-ai
  template:
    metadata:
      labels:
        app: geekform-ai
    spec:
      containers:
        - name: api
          image: geekform-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: geekform-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: geekform-ai
  namespace: geekform
spec:
  selector:
    app: geekform-ai
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
