trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'azure-pipelines.yml'
    exclude:
      - 'cleanup-pipeline.yml'

pool:
  name: UbuntuServer

variables:
  IMAGE_NAME: "portfolio-site"
  IMAGE_TAG: "latest"

stages:
  - stage: Build
    displayName: "Build Docker Image"
    jobs:
      - job: BuildDocker
        steps:
          - task: Bash@3
            displayName: "Build Docker Image"
            inputs:
              targetType: inline
              script: |
                cd portfolio-website
                eval $(minikube docker-env)
                docker build -t $(IMAGE_NAME):$(IMAGE_TAG) .

  - stage: Deploy
    displayName: "Deploy to Minikube"
    jobs:
      - job: DeployToK8s
        steps:
          - task: Bash@3
            displayName: "Apply Kubernetes Manifests"
            inputs:
              targetType: inline
              script: |
                kubectl get namespace portfolio || kubectl create namespace portfolio && kubectl apply -f k8s-manifests/ -n portfolio

