trigger: none

pool:
  name: UbuntuServer

variables:
  MINIKUBE_VERSION: 'latest'

steps:
- task: Bash@3
  displayName: 'Install Docker'
  inputs:
    targetType: 'inline'
    script: |
- task: Bash@3
  displayName: 'Install Docker'
  inputs:
    targetType: 'inline'
    script: |
      set -eux
      sudo apt-get update -y
      sudo apt-get install -y --no-install-recommends ca-certificates curl gnupg lsb-release
      sudo install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      sudo chmod a+r /etc/apt/keyrings/docker.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update -y
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      echo "Docker installation complete ✅"
- task: Bash@3
  displayName: 'Install Kubectl'
  inputs:
    targetType: 'inline'
    script: |
      set -e
      sudo apt-get update -y
      sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
      sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update -y
      echo "Installing Kubectl"
      sudo apt-get install -y kubectl
- task: Bash@3
  displayName: 'Install Minikube'
  inputs:
    targetType: 'inline'
    script: |
      set -e
      echo "Minikube installation ✅"
      curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      sudo dpkg -i minikube_latest_amd64.deb
      echo "Minikube installation finished✅"

    