# Secret-K8-Inject
trigger:
- none

pool:
  name: PredatorAgentPool
variables:
  - group: Cloudflare
stages:
  - stage: Inject
    displayName: "InjectSecret"
    jobs:
      - job: K8Inject
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
                      kubectl create secret generic cloudflare-secret \
                      --from-literal=tunnelToken=$(CLOUDFLARE_TOK) \
                      --namespace cloudflare --dry-run=client -o yaml | kubectl apply -f -