trigger: none

pool:
  name: PredatorAgentPool  # your agent with kubectl and trivy installed

jobs:
- job: TrivyScanCSV
  displayName: "Scan all cluster images with Trivy and export CSV"
  steps:
  - script: |
      echo "Listing all container images in cluster..."
      images=$(kubectl get pods --all-namespaces -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq)

      echo "Images found:"
      echo "$images"

      mkdir -p trivy-reports

      for image in $images; do
        echo "Scanning $image ..."
        filename=$(echo $image | tr '/:' '__')
        trivy image --format csv --output trivy-reports/$filename.csv $image || true
      done

      echo "CSV scan reports generated."
    displayName: "Run Trivy scans with CSV output"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'trivy-reports'
      ArtifactName: 'TrivyScanCSVReports'
      publishLocation: 'Container'
    displayName: "Publish Trivy CSV Scan Reports"
