trigger: none

pool:
  name: PredatorAgentPool  # Your agent with kubectl and trivy installed

jobs:
- job: TrivyScanSARIF
  displayName: "Scan all cluster images and publish SARIF results"
  steps:
  - script: |
      mkdir -p trivy-reports
      images=$(kubectl get pods --all-namespaces -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq)

      for image in $images; do
        filename=$(echo $image | tr '/:' '__')
        echo "Scanning $image ..."
        trivy image --format sarif --output trivy-reports/$filename.sarif $image || true
      done
    displayName: "Run Trivy scans and output SARIF"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'trivy-reports'
      ArtifactName: 'CodeAnalysisLogs'
      publishLocation: 'Container'
    displayName: "Publish SARIF Reports"
