trigger: none
pool:
  name: PredatorAgentPool
stages:
- stage: __default
  jobs:
  - job: TrivyScanAllImages
    displayName: "Scan all cluster images with Trivy"
    steps:
    - task: CmdLine@2
      displayName: "Run Trivy scans"
      inputs:
        script: |
          echo "Listing all container images in cluster..."
          images=$(kubectl get pods --all-namespaces -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq)

          echo "Images found:"
          echo "$images"

          mkdir -p trivy-reports

          for image in $images; do
            echo "Scanning $image ..."
            filename=$(echo $image | tr '/:' '__')
            trivy image --format json --output trivy-reports/$filename.json $image || true
          done

          echo "Scan complete."
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'trivy-reports'
        ArtifactName: 'TrivyScanReports'
        publishLocation: 'Container'
      displayName: "Publish Trivy Scan Reports"

