trigger: none

pool:
  name: PredatorAgentPool

variables:
  IMAGE_NAME: "main-website"
  IMAGE_TAG: "v1.0"
  K3S_DIR: "WebApps/main-site/k3s-manifest"

stages:
  - stage: Build
    displayName: "Build Docker Image"
    jobs:
      - job: BuildDocker
        displayName: "Build Local Docker Image"
        steps:
          - checkout: self

          - task: Bash@3
            displayName: "Build Docker Image for K3s"
            inputs:
              targetType: inline
              script: |
                echo "🧱 Building Docker image..."
                cd WebApps/main-site/
                docker build -t $(IMAGE_NAME):$(IMAGE_TAG) .

          - task: Bash@3
            displayName: "Import Image into K3s"
            inputs:
              targetType: inline
              script: |
                echo "📦 Exporting image..."
                docker save $(IMAGE_NAME):$(IMAGE_TAG) -o $(IMAGE_NAME).tar

                echo "🚀 Importing into K3s containerd..."
                sudo k3s ctr images import $(IMAGE_NAME).tar

  - stage: Deploy
    displayName: "Deploy to K3s"
    dependsOn: Build
    jobs:
      - job: DeployToK3s
        displayName: "Apply Kubernetes Manifests"
        steps:
          - checkout: self

          - task: Bash@3
            displayName: "Apply Deployment & Service"
            inputs:
              targetType: inline
              script: |
                echo "⚙️ Applying Kubernetes manifests..."
                kubectl apply -f $(K3S_DIR)/deployment.yaml
                kubectl apply -f $(K3S_DIR)/service.yaml

                echo "⏳ Waiting for rollout..."
                kubectl rollout status deployment/main-site

                echo "✅ Deployment complete!"

