trigger:
  branches:
    include:
      - main

pool:
  name: PredatorAgentPool

variables:
  - group: GitCreds          # Your variable group holding GIT_PAT
  - name: GITHUB_REPO_URL
    value: https://github.com/GeekWaveTT/GeekWaveTT.git

steps:
  - checkout: self

  - task: Bash@3
    displayName: "Sync Azure Repo to GitHub"
    inputs:
      targetType: inline
      script: |
        git config --global user.name "AzureDevOps Sync Bot"
        git config --global user.email "sync-bot@sync.dev"
        
        # Add GitHub remote using PAT
        git remote add github https://$(GIT_PAT)@github.com/GeekWaveTT/GeekWaveTT.git

        # Push to GitHub
        git push github HEAD:main --force
    env:
      GIT_PAT: $(GIT_PAT)
